name: checks

on: [push]

jobs:
  check:
    runs-on: [ubuntu-latest]
    name: Run Checks
    steps:
    - uses: actions/checkout@master
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "./"
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
